# Generated by Django 4.1.5 on 2023-01-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cortar_url_short_url_alter_cortar_url_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cortar_url',
            name='short_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
